/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ptcSistemaEscola;


import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static ptcSistemaEscola.Conexao.con;


/**
 *
 * @author samue
 */
public class tAluno extends javax.swing.JFrame {
DefaultTableModel model;
    /**
     * Creates new form tAluno
     */
    public tAluno() {
        initComponents();
        Conexao.Conectar(); 
        jTable1.getColumnModel().getColumn(0).setMaxWidth(120); 
        jTable1.getColumnModel().getColumn(1).setMaxWidth(260);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(420); 
        jTable1.getColumnModel().getColumn(3).setMaxWidth(260);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(190);
        model =  (DefaultTableModel) jTable1.getModel(); 
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        CarregarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfRA = new javax.swing.JTextField();
        cbxTurma1 = new javax.swing.JComboBox<>();
        tfAno = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxRA = new javax.swing.JComboBox<>();
        cbxTurma2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxAno = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnIncluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblAlunoID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro do Aluno/a");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("RA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Turma:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ano:");

        tfRA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbxTurma1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxTurma1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        try {
            tfAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfAno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar, Alterar e Excluir \n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        btnConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("RA:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Turma:");

        cbxRA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxRA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        cbxTurma2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxTurma2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Ano:");

        cbxAno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(cbxRA, 0, 314, Short.MAX_VALUE)
                            .addComponent(cbxTurma2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addComponent(cbxAno, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTurma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Cadastro do Aluno/a");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RA ", "Aluno", "Turma", "Ano"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(210);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(350);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(210);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(164);
        }

        btnIncluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblAlunoID.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        lblAlunoID.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfRA)
                                            .addComponent(cbxTurma1, 0, 250, Short.MAX_VALUE)
                                            .addComponent(tfAno)))
                                    .addComponent(lblAlunoID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(lblAlunoID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSair)
                            .addComponent(btnIncluir))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void CarregarCombo() {
        String sql;
        try
        {
            cbxTurma1.removeAllItems();
            cbxTurma2.removeAllItems();
            cbxRA.removeAllItems();
            cbxAno.removeAllItems();
            cbxTurma1.addItem("Selecione...");
            cbxTurma2.addItem("Selecione...");
            cbxRA.addItem("Selecione...");
            cbxAno.addItem("Selecione...");
            
            sql = "select Codigo from Turma ";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next())
            {
                cbxTurma1.addItem(rs.getString("Codigo"));
                cbxTurma2.addItem(rs.getString("Codigo"));
            }
            
            sql = "select RA from Aluno order by RA ASC";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                cbxRA.addItem(rs.getString("RA"));
            }  
            
            sql = "select distinct Ano from Aluno order by Ano ASC ";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                cbxAno.addItem(rs.getString("Ano"));
            }  
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao incluir os combos. "+e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        try{
            Conexao.con.close();
        }
        catch (Exception e){
            System.out.println(e);
        }
        tMenu menu = new tMenu();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        try
        {
            String sql;
            String ra = "",turma = "", ano  = "", limpacbx = "Selecione...";
            ra = tfRA.getText();
            sql = "select TurmaID from Turma where Codigo = '" + cbxTurma1.getSelectedItem() + "'";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next())
            {
                turma = rs.getString("TurmaID");
            }
            ano = tfAno.getText();
            
            if(ra.equals("") || turma.equals("") || ano.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Por Favor, preencha os dados corretamente!","ERRO",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                sql="INSERT INTO Aluno (RA,TurmaID,Ano) values " +
                "('" + ra + "'," + turma + "," + ano + ")";

                stm = con.prepareStatement(sql);
                stm.execute(sql);
                tfRA.setText("");
                tfAno.setText("");
                cbxTurma1.setSelectedItem(limpacbx);
                CarregarCombo();
                tfRA.requestFocus();
                model.setRowCount(0);
                JOptionPane.showMessageDialog( null, "Inclusão realizada com Sucesso! ","Sucesso",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao incluir, tente novamente "+e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String turma;
        int linha = jTable1.getSelectedRow();
        if (linha==-1)
        {
            JOptionPane.showMessageDialog(null,"Você deve selecionar uma linha.");
        }
        else{
            lblAlunoID.setText((String) jTable1.getValueAt(linha, 0));
            tfRA.setText((String) jTable1.getValueAt(linha, 1));
            turma = ((String) jTable1.getValueAt(linha, 3));
            cbxTurma1.setSelectedItem(turma);
            tfAno.setText((String) jTable1.getValueAt(linha, 4));
            tfRA.requestFocus();
            btnGravar.setEnabled(true);
            btnIncluir.setEnabled(false);
            btnConsultar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        try
        {
            String sql;
            String ra = "",turma = "", ano = "", limpacbx = "Selecione...";
            ra = tfRA.getText();
            sql = "select TurmaID from Turma where Codigo = '" + cbxTurma1.getSelectedItem() + "'";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next())
            {
                turma = rs.getString("TurmaID");
            }
            ano = tfAno.getText();
             
            if(ra.equals("") || turma.equals("") || ano.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Por Favor, preencha os dados corretamente!","ERRO",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                sql="UPDATE Aluno set RA = '" +ra +"',TurmaID = "+turma+",Ano = "+ano+""
                + " where AlunoID = "+lblAlunoID.getText(); 
                
                stm = con.prepareStatement(sql);
                stm.execute(sql);
                tfRA.setText("");
                tfAno.setText("");
                cbxTurma1.setSelectedItem(limpacbx);
                CarregarCombo();
                tfRA.requestFocus();
                model.setRowCount(0);
                btnIncluir.setEnabled(true);
                btnConsultar.setEnabled(true);
                btnAlterar.setEnabled(false);
                btnGravar.setEnabled(false);
                JOptionPane.showMessageDialog( null, "Alteração realizada com Sucesso! ","Sucesso",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao alterar, tente novamente "+e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = jTable1.getSelectedRow();
        if (linha==-1)
        {
            JOptionPane.showMessageDialog(null,"Você deve selecionar uma linha.");
        }
        else
        {
            int opcao = JOptionPane.showConfirmDialog(null,"Confirma exclusão","Excluindo...", JOptionPane.YES_NO_OPTION);
            String sql, codigo;
            codigo = (String) jTable1.getValueAt(linha, 0);
            if (opcao==0)
            {
                try
                {
                    sql="delete from Aluno where AlunoID= " + codigo;
                    Statement stm = con.prepareStatement(sql);
                    stm.execute(sql);
                    btnIncluir.setEnabled(true);
                    btnConsultar.setEnabled(true);
                    btnAlterar.setEnabled(false);
                    btnExcluir.setEnabled(false);
                    tfRA.requestFocus();
                    CarregarCombo();
                    JOptionPane.showMessageDialog(null, "Exclusão feita com Sucesso! ","Sucesso", JOptionPane.INFORMATION_MESSAGE);
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir, tente novamente " +e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else
            {
                tfRA.requestFocus();
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);
            }
            model.setRowCount(0);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String sql;
        String nomeTurma="",RA = "", ano = "", turmaID = "";
        String limpacbx = "Selecione..."; 
        model.setRowCount(0);
        nomeTurma = cbxTurma2.getSelectedItem().toString();
        RA = cbxRA.getSelectedItem().toString();    
        ano = cbxAno.getSelectedItem().toString();    
        try
        {
            if(!nomeTurma.equals("Selecione..."))
            {
                sql = "select TurmaID from turma where Codigo = '" + nomeTurma + "'";
                Statement stm = con.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                while(rs.next())
                {
                    turmaID = rs.getString("turmaID");
                }
            }
                        
            sql = "SELECT tabelaAluno.*,tabelaMatricula.Nome as NomeAluno, tabelaTurma.Codigo as TurmaCodigo, tabelaTurma.TurmaID "
            + "from Aluno tabelaAluno inner join Turma tabelaTurma ON tabelaTurma.TurmaID = tabelaAluno.TurmaID "
            + "left join matricula tabelaMatricula ON tabelaMatricula.RA = tabelaAluno.RA "
            + " Where 1 = 1 ";

            if(!nomeTurma.equals("Selecione..."))
            {
                sql = sql + " AND tabelaTurma.TurmaID  = " + turmaID;
            }
          
            if(!RA.equals("Selecione..."))
            {
                sql = sql + " AND tabelaAluno.RA  = '" + RA+"'";
            }
            if(!ano.equals("Selecione..."))
            {
                sql = sql + " AND tabelaAluno.Ano = " + ano;
            }
            sql = sql + " order by tabelaAluno.Ano";
            
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            rs.first();
            rs.getRow();
            if(rs.getRow() > 0){
                String[] linha = new String[]{rs.getString("AlunoID"),rs.getString("RA"),rs.getString("NomeAluno"),rs.getString("TurmaCodigo"),
                rs.getString("Ano")};
                model.addRow(linha);
                while(rs.next())
                {
                    linha = new String[]{rs.getString("AlunoID"),rs.getString("RA"),rs.getString("NomeAluno"),rs.getString("TurmaCodigo"),
                    rs.getString("Ano")}; 
                    model.addRow(linha);
                }
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
                cbxTurma2.setSelectedItem(limpacbx);
                cbxRA.setSelectedItem(limpacbx);
                cbxAno.setSelectedItem(limpacbx);
            }
            else
            {
                JOptionPane.showMessageDialog( null, "Não existe nenhum aluno com essas características","Erro",JOptionPane.INFORMATION_MESSAGE);
                cbxTurma2.setSelectedItem(limpacbx);
                cbxRA.setSelectedItem(limpacbx);
                cbxAno.setSelectedItem(limpacbx);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao consultar, tente novamente "+e,"ERRO:",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxAno;
    private javax.swing.JComboBox<String> cbxRA;
    private javax.swing.JComboBox<String> cbxTurma1;
    private javax.swing.JComboBox<String> cbxTurma2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAlunoID;
    private javax.swing.JFormattedTextField tfAno;
    private javax.swing.JTextField tfRA;
    // End of variables declaration//GEN-END:variables
}
