/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ptcSistemaEscola;

import ptcSistemaEscola.Conexao;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static ptcSistemaEscola.Conexao.con;

/**
 *
 * @author samue
 */
public class tAtividade extends javax.swing.JFrame {
DefaultTableModel model;
    /**
     * Creates new form tAtividades
     */
    public tAtividade() {
        initComponents();
        Conexao.Conectar(); 
        jTable1.getColumnModel().getColumn(0).setMaxWidth(120); 
        jTable1.getColumnModel().getColumn(1).setMaxWidth(420);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(420); 
        jTable1.getColumnModel().getColumn(3).setMaxWidth(420);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(420);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(420);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(260);
        jTable1.getColumnModel().getColumn(7).setMaxWidth(260);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(260);
        model =  (DefaultTableModel) jTable1.getModel(); 
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        CarregarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxDisciplina1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxProfessor2 = new javax.swing.JComboBox<>();
        cbxDisciplina2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbxTurma2 = new javax.swing.JComboBox<>();
        cbxAluno2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbxDescricao = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnIncluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbxTurma1 = new javax.swing.JComboBox<>();
        cbxProfessor1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxAluno1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfDataLancamento = new javax.swing.JFormattedTextField();
        tfDataEntrega = new javax.swing.JFormattedTextField();
        lblAtividadeID = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro das Atividades");
        setResizable(false);

        cbxDisciplina1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxDisciplina1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar, Alterar e Excluir \n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        btnConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Professor/a:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Disciplina:");

        cbxProfessor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxProfessor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        cbxDisciplina2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxDisciplina2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Turma:");
        jLabel12.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Aluno:");
        jLabel13.setToolTipText("");

        cbxTurma2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxTurma2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        cbxAluno2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxAluno2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Descrição:");
        jLabel14.setToolTipText("");

        cbxDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxDescricao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxDescricao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6)
                    .addComponent(cbxAluno2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxTurma2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxDisciplina2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxProfessor2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxProfessor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDisciplina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTurma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxAluno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Cadastro das Atividades");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Professor", "Disciplina", "Turma", "Aluno", "Descrição", "Data Lançamento", "Data Entrega", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(320);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(320);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(320);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(320);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(320);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(240);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(240);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(240);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Professor/a:");

        btnIncluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Disiciplina:");

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Turma:");

        cbxTurma1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxTurma1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        cbxProfessor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxProfessor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Aluno:");

        cbxAluno1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxAluno1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Descrição:");

        tfDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Valor:");

        tfValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Data Lançamento:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Data Entrega:");

        try {
            tfDataLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataLancamento.setText("");
        tfDataLancamento.setToolTipText("");
        tfDataLancamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        try {
            tfDataEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataEntrega.setText("");
        tfDataEntrega.setToolTipText("");
        tfDataEntrega.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblAtividadeID.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        jLabel15.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3))
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfDescricao)
                                            .addComponent(tfDataLancamento)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cbxDisciplina1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cbxTurma1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cbxProfessor1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cbxAluno1, 0, 250, Short.MAX_VALUE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(tfDataEntrega, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tfValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(309, 309, 309))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lblAtividadeID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbxProfessor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxDisciplina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbxTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbxAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAtividadeID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnIncluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarregarCombo() {
        String sql;
        try
        {
            cbxProfessor1.removeAllItems();
            cbxProfessor2.removeAllItems();
            cbxDisciplina1.removeAllItems();
            cbxDisciplina2.removeAllItems();
            cbxTurma1.removeAllItems();
            cbxTurma2.removeAllItems();
            cbxAluno1.removeAllItems();
            cbxAluno2.removeAllItems();
            cbxDescricao.removeAllItems();
            cbxProfessor1.addItem("Selecione...");
            cbxProfessor2.addItem("Selecione...");
            cbxDisciplina1.addItem("Selecione...");
            cbxDisciplina2.addItem("Selecione...");
            cbxTurma1.addItem("Selecione...");
            cbxTurma2.addItem("Selecione...");
            cbxAluno1.addItem("Selecione...");
            cbxAluno2.addItem("Selecione...");
            cbxDescricao.addItem("Selecione...");
            
            sql = "select Nome from Professor order by Nome asc ";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next())
            {
                cbxProfessor1.addItem(rs.getString("Nome"));
                cbxProfessor2.addItem(rs.getString("Nome"));
            }
            
            sql = "select Codigo from Disciplina order by Codigo ASC";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                cbxDisciplina1.addItem(rs.getString("Codigo"));
                cbxDisciplina2.addItem(rs.getString("Codigo"));
            }  
            
            sql = "select Codigo from Turma order by Codigo ASC ";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                cbxTurma1.addItem(rs.getString("Codigo"));
                cbxTurma2.addItem(rs.getString("Codigo"));
            } 
            
            sql = "select Nome from Matricula order by Nome ASC ";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                cbxAluno1.addItem(rs.getString("Nome"));
                cbxAluno2.addItem(rs.getString("Nome"));
            }
            
            sql = "select Descricao from Atividade order by Descricao ASC ";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                cbxDescricao.addItem(rs.getString("Descricao"));
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao incluir os combos. "+e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }
        
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        try{
            Conexao.con.close();
        }
        catch (Exception e){
            System.out.println(e);
        }
        tMenu menu = new tMenu();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        try
        {
            String sql;
            String professor = "",disciplina = "", turma  = "", aluno="", descricao="",dataLanc="",dataEntre="";
            String valor="", limpacbx = "Selecione...";
         
            sql = "select ProfessorID from Professor where Nome = '" + cbxProfessor1.getSelectedItem() + "'";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next())
            {
                professor = rs.getString("ProfessorID");
            }
            sql = "select DisciplinaID from Disciplina where Codigo = '" + cbxDisciplina1.getSelectedItem() + "'";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                disciplina = rs.getString("DisciplinaID");
            }
            sql = "select TurmaID from Turma where Codigo= '" + cbxTurma1.getSelectedItem() + "'";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                turma = rs.getString("TurmaID");
            }
            
            aluno = cbxAluno1.getSelectedItem().toString();
            if(!aluno.equals("Selecione...")){
                sql = "select AlunoID from Aluno tabelaAluno inner join Matricula tabelaMatricula on tabelaMatricula.Nome = '" + cbxAluno1.getSelectedItem() + "'";
                stm = con.createStatement();
                rs = stm.executeQuery(sql);
                while(rs.next())
                {
                    aluno = rs.getString("AlunoID");
                }
            }
                 
            descricao = tfDescricao.getText();
            String dia = tfDataLancamento.getText().substring(0, 2);
            String mes = tfDataLancamento.getText().substring(3, 5);
            String ano = tfDataLancamento.getText().substring(6);
            dataLanc = ano+"-"+mes+"-"+dia;
            dia = tfDataEntrega.getText().substring(0, 2);
            mes = tfDataEntrega.getText().substring(3, 5);
            ano = tfDataEntrega.getText().substring(6);
            dataEntre = ano+"-"+mes+"-"+dia;
            valor = tfValor.getText();
            
            if(professor.equals("") || disciplina.equals("") || turma.equals("")|| descricao.equals("")|| dataLanc.equals("")|| dataEntre.equals("")|| valor.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Por Favor, preencha os dados corretamente!","ERRO",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                if(!aluno.equals("Selecione...")){
                    sql="INSERT INTO Atividade (ProfessorID,DisciplinaID,TurmaID,AlunoID,Descricao,Data_Lancamento,Data_Entrega,Valor) values " +
                    "(" + professor + "," + disciplina + "," + turma +","+aluno+",'"+ descricao+"','"+dataLanc+"','"+dataEntre+"',"+valor+" )";
                }
                else{
                    sql="INSERT INTO Atividade (ProfessorID,DisciplinaID,TurmaID,Descricao,Data_Lancamento,Data_Entrega,Valor) values " +
                    "(" + professor + "," + disciplina + "," + turma +",'"+ descricao+"','"+dataLanc+"','"+dataEntre+"',"+valor+" )";
                }
                
               
                stm = con.prepareStatement(sql);
                stm.execute(sql);
                cbxProfessor1.setSelectedItem(limpacbx);
                cbxDisciplina1.setSelectedItem(limpacbx);
                cbxTurma1.setSelectedItem(limpacbx);
                cbxAluno1.setSelectedItem(limpacbx);
                tfDescricao.setText("");
                tfDataLancamento.setText("");
                tfDataEntrega.setText("");
                tfValor.setText("");
                CarregarCombo();
                cbxProfessor1.requestFocus();
                model.setRowCount(0);
                JOptionPane.showMessageDialog( null, "Inclusão realizada com Sucesso! ","Sucesso",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao incluir, tente novamente "+e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String sql;
        String nomeProfessor="",professorID="",nomeDisciplina="",disciplinaID="",nomeTurma="",turmaID="",nomeAluno="",alunoID="",descricao="";
        String limpacbx = "Selecione..."; 
        model.setRowCount(0);
        nomeProfessor = cbxProfessor2.getSelectedItem().toString();
        nomeDisciplina = cbxDisciplina2.getSelectedItem().toString();
        nomeTurma = cbxTurma2.getSelectedItem().toString();
        nomeAluno = cbxAluno2.getSelectedItem().toString();
        descricao = cbxDescricao.getSelectedItem().toString();      
           
        try
        {
            if(!nomeProfessor.equals("Selecione..."))
            {
                sql = "select ProfessorID from Professor where Nome = '" + nomeProfessor + "'";
                Statement stm = con.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                while(rs.next())
                {
                    professorID = rs.getString("ProfessorID");
                }
            }
            if(!nomeDisciplina.equals("Selecione..."))
            {
                sql = "select DisciplinaID from Disciplina where Codigo = '" + nomeDisciplina + "'";
                Statement stm = con.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                while(rs.next())
                {
                    disciplinaID = rs.getString("DisciplinaID");
                }
            }
            if(!nomeTurma.equals("Selecione..."))
            {
                sql = "select TurmaID from Turma where Codigo = '" + nomeTurma + "'";
                Statement stm = con.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                while(rs.next())
                {
                    turmaID = rs.getString("TurmaID");
                }
            }
            if(!nomeAluno.equals("Selecione..."))
            {
                sql = "select tabelaAluno.AlunoID from Aluno tabelaAluno inner join Matricula tabelaMatricula on  tabelaMatricula.RA = tabelaAluno.RA  where tabelaMatricula.Nome = '" + nomeAluno + "'";
                Statement stm = con.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                while(rs.next())
                {
                    alunoID = rs.getString("AlunoID");
                }
            }
                                   
            sql = "SELECT tabelaAtividade.*, tabelaProfessor.Nome as NomeProfessor, tabelaProfessor.ProfessorID, tabelaDisciplina.Codigo as DisciplinaCodigo,"
            + " tabelaDisciplina.DisciplinaID, tabelaTurma.Codigo as TurmaCodigo, tabelaTurma.TurmaID, tabelaAluno.AlunoID, tabelaMatricula.Nome as NomeAluno from Atividade tabelaAtividade "
            + " left join Professor tabelaProfessor ON tabelaProfessor.ProfessorID =  tabelaAtividade.ProfessorID"
            + " left join Disciplina tabelaDisciplina ON tabelaDisciplina.DisciplinaID = tabelaAtividade.DisciplinaID "
            + " left join Turma tabelaTurma ON tabelaTurma.TurmaID =  tabelaAtividade.TurmaID "
            + " left join Aluno tabelaAluno ON tabelaAluno.AlunoID  = tabelaAtividade.AlunoID "
            + " left join Matricula tabelaMatricula ON tabelaMatricula.RA = tabelaAluno.RA      "       
            + " Where 1 = 1 ";

            if(!nomeProfessor.equals("Selecione..."))
            {
                sql = sql + " AND tabelaProfessor.ProfessorID= " + professorID;
            }
          
            if(!nomeDisciplina.equals("Selecione..."))
            {
                sql = sql + " AND tabelaDisciplina.DisciplinaID  = '" + disciplinaID+"'";
            }
            if(!nomeTurma.equals("Selecione..."))
            {
                sql = sql + " AND tabelaTurma.TurmaID = " + turmaID;
            }
            if(!nomeAluno.equals("Selecione..."))
            {
                sql = sql + " AND tabelaMatricula.Nome  = '" + nomeAluno + "'";
            }
            if(!descricao.equals("Selecione..."))
            {
                sql = sql + " AND tabelaAtividade.Descricao  = '"+ descricao+"'";
            }
            sql = sql + " order by tabelaAtividade.Descricao";
            
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            rs.first();
            rs.getRow();
            if(rs.getRow() > 0){
                String[] linha = new String[]{rs.getString("AtividadeID"),rs.getString("NomeProfessor"),rs.getString("DisciplinaCodigo"),rs.getString("TurmaCodigo"),
                rs.getString("NomeAluno"),rs.getString("Descricao"),rs.getString("Data_Lancamento"),rs.getString("Data_Entrega"),rs.getString("Valor")};
                model.addRow(linha);
                while(rs.next())
                {
                    linha = new String[]{rs.getString("AtividadeID"),rs.getString("NomeProfessor"),rs.getString("DisciplinaCodigo"),rs.getString("TurmaCodigo"),
                rs.getString("NomeAluno"),rs.getString("Descricao"),rs.getString("Data_Lancamento"),rs.getString("Data_Entrega"),rs.getString("Valor")};
                    model.addRow(linha);
                }
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
                cbxProfessor2.setSelectedItem(limpacbx);
                cbxDisciplina2.setSelectedItem(limpacbx);
                cbxTurma2.setSelectedItem(limpacbx);
                cbxAluno2.setSelectedItem(limpacbx);
                cbxDescricao.setSelectedItem(limpacbx);
                
            }
            else
            {
                JOptionPane.showMessageDialog( null, "Não existe nenhuma Atividade com essas características","Erro",JOptionPane.INFORMATION_MESSAGE);
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao consultar, tente novamente "+e,"ERRO:",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String professor, disciplina, turma, aluno, dataLanc,dataEntre;
        int linha = jTable1.getSelectedRow();
        if (linha==-1)
        {
            JOptionPane.showMessageDialog(null,"Você deve selecionar uma linha.");
        }
        else{
            lblAtividadeID.setText((String) jTable1.getValueAt(linha, 0));
            professor = ((String) jTable1.getValueAt(linha, 1));
            cbxProfessor1.setSelectedItem(professor);
            disciplina = ((String) jTable1.getValueAt(linha, 2));
            cbxDisciplina1.setSelectedItem(disciplina);
            turma = ((String) jTable1.getValueAt(linha, 3));
            cbxTurma1.setSelectedItem(turma);
            aluno = ((String) jTable1.getValueAt(linha, 4));
            if(aluno != null && !aluno.equals("")){
                cbxAluno1.setSelectedItem(aluno);
            }
            else{
                aluno = "Selecione...";
                cbxAluno1.setSelectedItem(aluno);
            }
            tfDescricao.setText((String) jTable1.getValueAt(linha, 5));
            dataLanc = (String) jTable1.getValueAt(linha, 6);
            String dia = dataLanc.substring(8, 10);
            String mes = dataLanc.substring(5, 7);
            String ano = dataLanc.substring(0,4);
            dataLanc = dia+mes+ano;
            tfDataLancamento.setText(dataLanc);
            dataEntre = (String) jTable1.getValueAt(linha, 7);
            dia = dataEntre.substring(8, 10);
            mes = dataEntre.substring(5, 7);
            ano = dataEntre.substring(0,4);
            dataEntre = dia+mes+ano;
            tfDataEntrega.setText(dataEntre);
            tfValor.setText((String) jTable1.getValueAt(linha, 8));
            cbxProfessor1.requestFocus();
            btnGravar.setEnabled(true);
            btnIncluir.setEnabled(false);
            btnConsultar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        try
        {
            String sql;
            String professor = "",disciplina = "", turma  = "", aluno="", descricao="",dataLanc="",dataEntre="";
            String valor="", limpacbx = "Selecione...";
         
            sql = "select ProfessorID from Professor where Nome = '" + cbxProfessor1.getSelectedItem() + "'";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next())
            {
                professor = rs.getString("ProfessorID");
            }
            sql = "select DisciplinaID from Disciplina where Codigo = '" + cbxDisciplina1.getSelectedItem() + "'";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                disciplina = rs.getString("DisciplinaID");
            }
            sql = "select TurmaID from Turma where Codigo= '" + cbxTurma1.getSelectedItem() + "'";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                turma = rs.getString("TurmaID");
            }
            
            aluno = cbxAluno1.getSelectedItem().toString();
            if(!aluno.equals("Selecione...")){
                sql = "select AlunoID from Aluno tabelaAluno inner join Matricula tabelaMatricula on tabelaMatricula.Nome = '" + cbxAluno1.getSelectedItem() + "'";
                stm = con.createStatement();
                rs = stm.executeQuery(sql);
                while(rs.next())
                {
                    aluno = rs.getString("AlunoID");
                }
            }
              
            descricao = tfDescricao.getText();
            String dia = tfDataLancamento.getText().substring(0, 2);
            String mes = tfDataLancamento.getText().substring(3, 5);
            String ano = tfDataLancamento.getText().substring(6);
            dataLanc = ano+"-"+mes+"-"+dia;
            dia = tfDataEntrega.getText().substring(0, 2);
            mes = tfDataEntrega.getText().substring(3, 5);
            ano = tfDataEntrega.getText().substring(6);
            dataEntre = ano+"-"+mes+"-"+dia;
            valor = tfValor.getText();
            
            if(professor.equals("") || disciplina.equals("") || turma.equals("")|| descricao.equals("")|| dataLanc.equals("")|| dataEntre.equals("")|| valor.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Por Favor, preencha os dados corretamente!","ERRO",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                if(!aluno.equals("Selecione...")){
                    sql="UPDATE Atividade SET ProfessorID ="+professor+",DisciplinaID ="+disciplina+",TurmaID="+turma+",AlunoID="+aluno+","
                    + "Descricao='"+descricao+"',Data_Lancamento='"+dataLanc+"',Data_Entrega='"+dataEntre+"',Valor="+valor+" where AtividadeID = "+lblAtividadeID.getText(); 
                }
                else{
                    sql="UPDATE Atividade SET ProfessorID ="+professor+",DisciplinaID ="+disciplina+",TurmaID="+turma+",AlunoID=null ,"
                    + "Descricao='"+descricao+"',Data_Lancamento='"+dataLanc+"',Data_Entrega='"+dataEntre+"',Valor="+valor+" where AtividadeID = "+lblAtividadeID.getText(); 
                }
                
                stm = con.prepareStatement(sql);
                stm.execute(sql);
                cbxProfessor1.setSelectedItem(limpacbx);
                cbxDisciplina1.setSelectedItem(limpacbx);
                cbxTurma1.setSelectedItem(limpacbx);
                cbxAluno1.setSelectedItem(limpacbx);
                tfDescricao.setText("");
                tfDataLancamento.setText("");
                tfDataEntrega.setText("");
                tfValor.setText("");
                CarregarCombo();
                cbxProfessor1.requestFocus();
                model.setRowCount(0);
                btnIncluir.setEnabled(true);
                btnConsultar.setEnabled(true);
                btnAlterar.setEnabled(false);
                btnGravar.setEnabled(false);
                JOptionPane.showMessageDialog( null, "Alteração realizada com Sucesso! ","Sucesso",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao alterar, tente novamente "+e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = jTable1.getSelectedRow();
        if (linha==-1)
        {
            JOptionPane.showMessageDialog(null,"Você deve selecionar uma linha.");
        }
        else
        {
            int opcao = JOptionPane.showConfirmDialog(null,"Confirma exclusão","Excluindo...", JOptionPane.YES_NO_OPTION);
            String sql, codigo;
            codigo = (String) jTable1.getValueAt(linha, 0);
            if (opcao==0)
            {
                try
                {
                    sql="delete from Atividade where AtividadeID= " + codigo;
                    Statement stm = con.prepareStatement(sql);
                    stm.execute(sql);
                    btnIncluir.setEnabled(true);
                    btnConsultar.setEnabled(true);
                    btnAlterar.setEnabled(false);
                    btnExcluir.setEnabled(false);
                    cbxProfessor1.requestFocus();
                    CarregarCombo();
                    JOptionPane.showMessageDialog(null, "Exclusão feita com Sucesso! ","Sucesso", JOptionPane.INFORMATION_MESSAGE);
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir, tente novamente " +e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else
            {
                cbxProfessor1.requestFocus();
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);
            }
            model.setRowCount(0);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tAtividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxAluno1;
    private javax.swing.JComboBox<String> cbxAluno2;
    private javax.swing.JComboBox<String> cbxDescricao;
    private javax.swing.JComboBox<String> cbxDisciplina1;
    private javax.swing.JComboBox<String> cbxDisciplina2;
    private javax.swing.JComboBox<String> cbxProfessor1;
    private javax.swing.JComboBox<String> cbxProfessor2;
    private javax.swing.JComboBox<String> cbxTurma1;
    private javax.swing.JComboBox<String> cbxTurma2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAtividadeID;
    private javax.swing.JFormattedTextField tfDataEntrega;
    private javax.swing.JFormattedTextField tfDataLancamento;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
