/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ptcSistemaEscola;

import ptcSistemaEscola.Conexao;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static ptcSistemaEscola.Conexao.con;

/**
 *
 * @author samue
 */
public class tFormaçao extends javax.swing.JFrame {
DefaultTableModel model;
    /**
     * Creates new form tFormaçao
     */
    public tFormaçao() {
        initComponents();
        Conexao.Conectar(); 
        jTable1.getColumnModel().getColumn(0).setMaxWidth(120); 
        jTable1.getColumnModel().getColumn(1).setMaxWidth(420);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(240); 
        jTable1.getColumnModel().getColumn(3).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(420);
        jTable1.getColumnModel().getColumn(7).setMaxWidth(420);
        model =  (DefaultTableModel) jTable1.getModel(); 
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        CarregarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxProfessor2 = new javax.swing.JComboBox<>();
        cbxHabilitacao = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnIncluir = new javax.swing.JButton();
        cbxProfessor1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfInstituicao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfCurso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfTCC = new javax.swing.JTextField();
        tfHabilitacao = new javax.swing.JTextField();
        tfAnoInicio = new javax.swing.JFormattedTextField();
        tfAnoConclusao = new javax.swing.JFormattedTextField();
        lblProfessorID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro Formação do Professor/a");
        setResizable(false);

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Cadastro Formação do Professor/a");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Professor/a:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar, Alterar e Excluir \n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        btnConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Professor/a:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Habilitação:");

        cbxProfessor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxProfessor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        cbxHabilitacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxHabilitacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxHabilitacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxProfessor2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxProfessor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxHabilitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Professor/a", "Instituição", "Curso", "Ano_Inicio", "Ano_Conclusão", "TCC", "Habilitação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(320);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(210);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(210);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(210);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(210);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(320);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(320);
        }

        btnIncluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        cbxProfessor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxProfessor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Instituição:");

        tfInstituicao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Curso:");

        tfCurso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Ano de Ínicio:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Ano de Conclusão:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("TCC:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Habilitação:");

        tfTCC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfHabilitacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        try {
            tfAnoInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfAnoConclusao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblProfessorID.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        lblProfessorID.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel8))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfHabilitacao, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                                    .addComponent(tfTCC, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                                    .addComponent(tfAnoConclusao)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(tfAnoInicio))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfInstituicao)
                                            .addComponent(tfCurso)
                                            .addComponent(cbxProfessor1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(lblProfessorID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(217, 217, 217)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbxProfessor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProfessorID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfAnoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfAnoConclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfTCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfHabilitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnIncluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarregarCombo() {
        String sql;
        try
        {
            cbxProfessor1.removeAllItems();
            cbxProfessor2.removeAllItems();
            cbxHabilitacao.removeAllItems();
            cbxProfessor1.addItem("Selecione...");
            cbxProfessor2.addItem("Selecione...");
            cbxHabilitacao.addItem("Selecione...");
                        
            sql = "select Nome from Professor order by Nome ASC";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next())
            {
                cbxProfessor1.addItem(rs.getString("Nome"));
                cbxProfessor2.addItem(rs.getString("Nome"));
            }
            
            sql = "select Habilitacao from Formacao";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                cbxHabilitacao.addItem(rs.getString("Habilitacao"));
            }  
                    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao incluir os combos. "+e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        try{
            Conexao.con.close();
        }
        catch (Exception e){
            System.out.println(e);
        }
        tMenu menu = new tMenu();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        try
        {
            String sql;
            String professor = "",instituicao = "", curso  = "",anoInicio  = "", anoConclusao  = "", tcc  = "", habilitacao  = ""; 
            String limpacbx = "Selecione...";
            
            sql = "select ProfessorID from Professor where Nome = '" + cbxProfessor1.getSelectedItem() + "'";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next())
            {
                professor = rs.getString("ProfessorID");
            }
            instituicao = tfInstituicao.getText();
            curso = tfCurso.getText();
            anoInicio = tfAnoInicio.getText();
            anoConclusao = tfAnoConclusao.getText();
            tcc = tfTCC.getText();
            habilitacao = tfHabilitacao.getText();
           
            
            if(professor.equals("") || instituicao.equals("") || curso.equals("")|| anoInicio.equals("")|| anoConclusao.equals("")|| habilitacao.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Por Favor, preencha os dados corretamente!","ERRO",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                sql="INSERT INTO Formacao (ProfessorID,Instituicao,Curso,Ano_Inicio,Ano_Conclusao,TCC,Habilitacao) values " +
                "("+ professor +",'"+ instituicao +"','" + curso + "'," + anoInicio + ","+anoConclusao+",'"+tcc+"','"+habilitacao+"')";

                stm = con.prepareStatement(sql);
                stm.execute(sql);
                cbxProfessor1.setSelectedItem(limpacbx);
                tfInstituicao.setText("");
                tfCurso.setText("");
                tfAnoInicio.setText("");
                tfAnoConclusao.setText("");
                tfTCC.setText("");
                tfHabilitacao.setText("");
                CarregarCombo();
                cbxProfessor1.requestFocus();
                model.setRowCount(0);
                JOptionPane.showMessageDialog( null, "Inclusão realizada com Sucesso! ","Sucesso",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao incluir, tente novamente "+e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = jTable1.getSelectedRow();
        if (linha==-1)
        {
            JOptionPane.showMessageDialog(null,"Você deve selecionar uma linha.");
        }
        else
        {
            int opcao = JOptionPane.showConfirmDialog(null,"Confirma exclusão","Excluindo...", JOptionPane.YES_NO_OPTION);
            String sql, codigo;
            codigo = (String) jTable1.getValueAt(linha, 0);
            if (opcao==0)
            {
                try
                {
                    sql="delete from Formacao where ProfessorID= " + codigo;
                    Statement stm = con.prepareStatement(sql);
                    stm.execute(sql);
                    btnIncluir.setEnabled(true);
                    btnConsultar.setEnabled(true);
                    btnAlterar.setEnabled(false);
                    btnExcluir.setEnabled(false);
                    cbxProfessor1.requestFocus();
                    CarregarCombo();
                    JOptionPane.showMessageDialog(null, "Exclusão feita com Sucesso! ","Sucesso", JOptionPane.INFORMATION_MESSAGE);
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir, tente novamente " +e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else
            {
                cbxProfessor1.requestFocus();
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);
            }
            model.setRowCount(0);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String professor;
        int linha = jTable1.getSelectedRow();
        if (linha==-1)
        {
            JOptionPane.showMessageDialog(null,"Você deve selecionar uma linha.");
        }
        else{
            lblProfessorID.setText((String) jTable1.getValueAt(linha, 0));
            professor = ((String) jTable1.getValueAt(linha, 1));
            cbxProfessor1.setSelectedItem(professor);
            tfInstituicao.setText((String) jTable1.getValueAt(linha, 2));
            tfCurso.setText((String) jTable1.getValueAt(linha, 3));
            tfAnoInicio.setText((String) jTable1.getValueAt(linha, 4));
            tfAnoConclusao.setText((String) jTable1.getValueAt(linha, 5));
            tfTCC.setText((String) jTable1.getValueAt(linha, 6));
            tfHabilitacao.setText((String) jTable1.getValueAt(linha, 7));
            cbxProfessor1.requestFocus();
            btnGravar.setEnabled(true);
            btnIncluir.setEnabled(false);
            btnConsultar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        try
        {
            String sql;
            String professor = "",instituicao = "", curso  = "",anoInicio  = "", anoConclusao  = "", tcc  = "", habilitacao  = ""; 
            String limpacbx = "Selecione...";
            
            sql = "select ProfessorID from Professor where Nome = '" + cbxProfessor1.getSelectedItem() + "'";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next())
            {
                professor = rs.getString("ProfessorID");
            }
            instituicao = tfInstituicao.getText();
            curso = tfCurso.getText();
            anoInicio = tfAnoInicio.getText();
            anoConclusao = tfAnoConclusao.getText();
            tcc = tfTCC.getText();
            habilitacao = tfHabilitacao.getText();
           
            
            if(professor.equals("") || instituicao.equals("") || curso.equals("")|| anoInicio.equals("")|| anoConclusao.equals("")|| habilitacao.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Por Favor, preencha os dados corretamente!","ERRO",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                sql="UPDATE Formacao set ProfessorID = '" + professor +"',Instituicao = '"+instituicao+"', Curso = '"+curso+"'"+
                ", Ano_Inicio = '"+anoInicio+"',Ano_Conclusao = '"+anoConclusao+"',TCC = '"+tcc+"',Habilitacao = '"+habilitacao+
                "' where ProfessorID = "+lblProfessorID.getText(); 
                
                stm = con.prepareStatement(sql);
                stm.execute(sql);
                cbxProfessor1.setSelectedItem(limpacbx);
                tfInstituicao.setText("");
                tfCurso.setText("");
                tfAnoInicio.setText("");
                tfAnoConclusao.setText("");
                tfTCC.setText("");
                tfHabilitacao.setText("");
                CarregarCombo();
                cbxProfessor1.requestFocus();
                model.setRowCount(0);
                btnIncluir.setEnabled(true);
                btnConsultar.setEnabled(true);
                btnAlterar.setEnabled(false);
                btnGravar.setEnabled(false);
                JOptionPane.showMessageDialog( null, "Alteração realizada com Sucesso! ","Sucesso",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao alterar, tente novamente "+e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String sql;
        String nomeProfessor="",habilitacao = "", professorID = "";
        String limpacbx = "Selecione..."; 
        model.setRowCount(0);
        nomeProfessor = cbxProfessor2.getSelectedItem().toString();
        habilitacao = cbxHabilitacao.getSelectedItem().toString();    
          
        try
        {
            if(!nomeProfessor.equals("Selecione..."))
            {
                sql = "select ProfessorID from Professor where Nome = '" + nomeProfessor + "'";
                Statement stm = con.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                while(rs.next())
                {
                    professorID = rs.getString("ProfessorID");
                }
            }
                        
            sql = "SELECT tabelaFormacao.*,tabelaProfessor.Nome as NomeProfessor, tabelaProfessor.ProfessorID "
            + "from Professor tabelaProfessor inner join Formacao tabelaFormacao ON tabelaFormacao.ProfessorID = tabelaProfessor.ProfessorID "
            + "Where 1 = 1 ";

            if(!nomeProfessor.equals("Selecione..."))
            {
                sql = sql + " AND tabelaProfessor.ProfessorID  = " + professorID;
            }
          
            if(!habilitacao.equals("Selecione..."))
            {
                sql = sql + " AND tabelaFormacao.Habilitacao  = '" + habilitacao+"'";
            }
            sql = sql + " order by tabelaProfessor.Nome";

            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            rs.first();
            rs.getRow();
            if(rs.getRow() > 0){
                String[] linha = new String[]{rs.getString("ProfessorID"),rs.getString("NomeProfessor"),rs.getString("Instituicao"),rs.getString("Curso"),
                rs.getString("Ano_Inicio"),rs.getString("Ano_Conclusao"),rs.getString("TCC"),rs.getString("Habilitacao")};
                model.addRow(linha);
                while(rs.next())
                {
                    linha = new String[]{rs.getString("ProfessorID"),rs.getString("NomeProfessor"),rs.getString("Instituicao"),rs.getString("Curso"),
                    rs.getString("Ano_Inicio"),rs.getString("Ano_Conclusao"),rs.getString("TCC"),rs.getString("Habilitacao")};
                    model.addRow(linha);
                }
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
                cbxProfessor2.setSelectedItem(limpacbx);
                cbxHabilitacao.setSelectedItem(limpacbx);
            }
            else
            {
                JOptionPane.showMessageDialog( null, "Não existe essa formação ou com esse professor","Erro",JOptionPane.INFORMATION_MESSAGE);
                cbxProfessor2.setSelectedItem(limpacbx);
                cbxHabilitacao.setSelectedItem(limpacbx);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao consultar, tente novamente "+e,"ERRO:",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tFormaçao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tFormaçao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tFormaçao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tFormaçao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tFormaçao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxHabilitacao;
    private javax.swing.JComboBox<String> cbxProfessor1;
    private javax.swing.JComboBox<String> cbxProfessor2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblProfessorID;
    private javax.swing.JFormattedTextField tfAnoConclusao;
    private javax.swing.JFormattedTextField tfAnoInicio;
    private javax.swing.JTextField tfCurso;
    private javax.swing.JTextField tfHabilitacao;
    private javax.swing.JTextField tfInstituicao;
    private javax.swing.JTextField tfTCC;
    // End of variables declaration//GEN-END:variables
}
