/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ptcSistemaEscola;

/**
 *
 * @author samue
 */
public class tMenu extends javax.swing.JFrame {

    /**
     * Creates new form tMenu
     */
    public tMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnCurso = new javax.swing.JMenuItem();
        mnTurma = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnAluno = new javax.swing.JMenuItem();
        mnMatricula = new javax.swing.JMenuItem();
        mnPagamento = new javax.swing.JMenuItem();
        mnAluno_Turma = new javax.swing.JMenuItem();
        mnProfessor = new javax.swing.JMenuItem();
        mnFormação = new javax.swing.JMenuItem();
        mnDisciplina = new javax.swing.JMenuItem();
        mnAtividades = new javax.swing.JMenuItem();
        mnNota = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("Cadastro");

        mnCurso.setText("Curso");
        mnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCursoActionPerformed(evt);
            }
        });
        jMenu1.add(mnCurso);

        mnTurma.setText("Turma");
        mnTurma.setToolTipText("");
        mnTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTurmaActionPerformed(evt);
            }
        });
        jMenu1.add(mnTurma);

        jMenu3.setText("Aluno/a");

        mnAluno.setText("RA");
        mnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlunoActionPerformed(evt);
            }
        });
        jMenu3.add(mnAluno);

        mnMatricula.setText("Matrícula");
        mnMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMatriculaActionPerformed(evt);
            }
        });
        jMenu3.add(mnMatricula);

        mnPagamento.setText("Pagamento");
        mnPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPagamentoActionPerformed(evt);
            }
        });
        jMenu3.add(mnPagamento);

        jMenu1.add(jMenu3);

        mnAluno_Turma.setText("Detalhes Turma");
        mnAluno_Turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAluno_TurmaActionPerformed(evt);
            }
        });
        jMenu1.add(mnAluno_Turma);

        mnProfessor.setText("Professor/a");
        mnProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProfessorActionPerformed(evt);
            }
        });
        jMenu1.add(mnProfessor);

        mnFormação.setText("Formação");
        mnFormação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFormaçãoActionPerformed(evt);
            }
        });
        jMenu1.add(mnFormação);

        mnDisciplina.setText("Disciplina");
        mnDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDisciplinaActionPerformed(evt);
            }
        });
        jMenu1.add(mnDisciplina);

        mnAtividades.setText("Atividade");
        mnAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAtividadesActionPerformed(evt);
            }
        });
        jMenu1.add(mnAtividades);

        mnNota.setText("Nota");
        mnNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNotaActionPerformed(evt);
            }
        });
        jMenu1.add(mnNota);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");

        mnSair.setText("Encerrar Programa");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenu2.add(mnSair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlunoActionPerformed
        tAluno tAluno = new tAluno();
        tAluno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnAlunoActionPerformed

    private void mnMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMatriculaActionPerformed
        tMatricula_Aluno tMatricula_A = new tMatricula_Aluno();
        tMatricula_A.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnMatriculaActionPerformed

    private void mnAluno_TurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAluno_TurmaActionPerformed
        tTurma_Det tTurma_Det = new tTurma_Det();
        tTurma_Det.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnAluno_TurmaActionPerformed

    private void mnNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNotaActionPerformed
        tNota tNota = new tNota();
        tNota.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnNotaActionPerformed

    private void mnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCursoActionPerformed
        tCurso tCurso = new tCurso();
        tCurso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnCursoActionPerformed

    private void mnFormaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFormaçãoActionPerformed
        tFormaçao tFormaçao = new tFormaçao();
        tFormaçao.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnFormaçãoActionPerformed

    private void mnDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDisciplinaActionPerformed
        tDisciplina tDisciplina = new tDisciplina();
        tDisciplina.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnDisciplinaActionPerformed

    private void mnPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPagamentoActionPerformed
        tPagamento tPagamento = new tPagamento();
        tPagamento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnPagamentoActionPerformed

    private void mnProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProfessorActionPerformed
        tProfessor tProfessor = new tProfessor();
        tProfessor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnProfessorActionPerformed

    private void mnTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTurmaActionPerformed
        tTurma tTurma = new tTurma();
        tTurma.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnTurmaActionPerformed

    private void mnAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAtividadesActionPerformed
        tAtividade tAtividade = new tAtividade();
        tAtividade.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnAtividadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnAluno;
    private javax.swing.JMenuItem mnAluno_Turma;
    private javax.swing.JMenuItem mnAtividades;
    private javax.swing.JMenuItem mnCurso;
    private javax.swing.JMenuItem mnDisciplina;
    private javax.swing.JMenuItem mnFormação;
    private javax.swing.JMenuItem mnMatricula;
    private javax.swing.JMenuItem mnNota;
    private javax.swing.JMenuItem mnPagamento;
    private javax.swing.JMenuItem mnProfessor;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnTurma;
    // End of variables declaration//GEN-END:variables
}
