/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ptcSistemaEscola;

import ptcSistemaEscola.Conexao;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static ptcSistemaEscola.Conexao.con;

/**
 *
 * @author samue
 */
public class tPagamento extends javax.swing.JFrame {
DefaultTableModel model;
    /**
     * Creates new form tPagamento
     */
    public tPagamento() {
        initComponents();
        Conexao.Conectar(); 
        jTable1.getColumnModel().getColumn(0).setMaxWidth(120); 
        jTable1.getColumnModel().getColumn(1).setMaxWidth(420);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(240); 
        jTable1.getColumnModel().getColumn(3).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(7).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(9).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(10).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(11).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(12).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(13).setMaxWidth(240);
        jTable1.getColumnModel().getColumn(14).setMaxWidth(240);
        model =  (DefaultTableModel) jTable1.getModel(); 
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        CarregarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxRA1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbxRA2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxResp = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnIncluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfNumeroBoleto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfValorPago = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfMetodoPagamento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfNumeroCheque = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfOperadoraCartao = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfBanco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfAgencia = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfConta = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lblPagamentoID = new javax.swing.JLabel();
        tfVencimento = new javax.swing.JFormattedTextField();
        tfDataPagamento = new javax.swing.JFormattedTextField();
        tfValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro dos Pagamentos");
        setResizable(false);

        cbxRA1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxRA1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar, Alterar e Excluir \n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        btnConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("RA:");

        cbxRA2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxRA2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Responsável Financeiro");

        cbxResp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxResp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxResp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxRA2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxRA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Cadastro dos Pagamentos ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Responsável Financeiro", "RA", "Número Boleto", "Vencimento", "Valor", "Descrição", "Data Pagamento", "Valor Pago", "Método Pagamento", "Operadora Cartão", "Banco", "Agencia", "Conta", "Número Cheque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(320);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(210);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(11).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(12).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(13).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(14).setPreferredWidth(190);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("RA:");

        btnIncluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Número Boleto:");

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Vencimento:");

        tfNumeroBoleto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Valor:");

        tfDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Descrição:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Data de Pagamento:");

        tfValorPago.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Valor Pago:");

        tfMetodoPagamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Método Pagamento:");

        tfNumeroCheque.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Número Cheque:");

        tfOperadoraCartao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Operadora Cartão:");

        tfBanco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Banco:");

        tfAgencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Agencia:");

        tfConta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Conta:");

        lblPagamentoID.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        lblPagamentoID.setText("jLabel6");
        lblPagamentoID.setEnabled(false);

        try {
            tfVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfVencimento.setText("");
        tfVencimento.setToolTipText("");
        tfVencimento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        try {
            tfDataPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataPagamento.setText("");
        tfDataPagamento.setToolTipText("");
        tfDataPagamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel13))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfAgencia)
                                            .addComponent(tfOperadoraCartao)
                                            .addComponent(tfNumeroCheque)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfDataPagamento))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfMetodoPagamento))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3))
                                            .addComponent(jLabel8))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNumeroBoleto, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbxRA1, 0, 357, Short.MAX_VALUE)
                                            .addComponent(tfVencimento)
                                            .addComponent(tfValor)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(61, 61, 61)
                                        .addComponent(tfValorPago))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(68, 68, 68)
                                        .addComponent(tfDescricao)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(285, 285, 285)
                                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel17)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(tfBanco)))
                                            .addComponent(lblPagamentoID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbxRA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPagamentoID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNumeroBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tfMetodoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfOperadoraCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(tfBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tfAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tfNumeroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnIncluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarregarCombo() {
        String sql;
        try
        {
            cbxRA1.removeAllItems();
            cbxRA2.removeAllItems();
            cbxResp.removeAllItems();
            cbxRA1.addItem("Selecione...");
            cbxRA2.addItem("Selecione...");
            cbxResp.addItem("Selecione...");
        
            sql = "select RA from Aluno";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next())
            {
                cbxRA1.addItem(rs.getString("RA"));
                cbxRA2.addItem(rs.getString("RA"));
            }
            
            sql = "select Responsavel_Financeiro from Matricula";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                cbxResp.addItem(rs.getString("Responsavel_Financeiro"));
            }
                       
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao incluir os combos. "+e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }
  
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        try{
            Conexao.con.close();
        }
        catch (Exception e){
            System.out.println(e);
        }
        tMenu menu = new tMenu();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        try
        {
            String sql;
            String ra = "",numeroBoleto, vencimento, valor, descricao = "";  
            String dataPagamento = "", valorPago="", metodoPagamento="", operadoraCartao="";
            String banco="", agencia="", conta="", numeroCheque="",limpacbx = "Selecione...";
            
            ra = cbxRA1.getSelectedItem().toString(); 
            numeroBoleto = tfNumeroBoleto.getText();
            String dia = tfVencimento.getText().substring(0, 2);
            String mes = tfVencimento.getText().substring(3, 5);
            String ano = tfVencimento.getText().substring(6);
            vencimento = ano+"-"+mes+"-"+dia;
            valor = tfValor.getText();
            descricao = tfDescricao.getText();     
            dia = tfDataPagamento.getText().substring(0, 2);
            mes = tfDataPagamento.getText().substring(3, 5);
            ano = tfDataPagamento.getText().substring(6);
            dataPagamento = ano+"-"+mes+"-"+dia;
            valorPago = tfValorPago.getText();       
            metodoPagamento = tfMetodoPagamento.getText();        
            operadoraCartao = tfOperadoraCartao.getText();      
            banco = tfBanco.getText();       
            agencia = tfAgencia.getText();     
            conta = tfConta.getText();    
            numeroCheque = tfNumeroCheque.getText();     
                               
            if(ra.equals("") || numeroBoleto.equals("") || vencimento.equals("") || valor.equals("") || dataPagamento.equals("") || valorPago.equals("") || metodoPagamento.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Por Favor, preencha os dados corretamente!","ERRO",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                sql="INSERT INTO Pagamento (RA,Numero_Boleto, Vencimento, Valor, Descricao, Data_Pagamento, Valor_Pago, Metodo_Pagamento,"
                + " Operadora_Cartao, Banco, Agencia, Conta, Numero_Cheque) values " +
                "('" + ra + "','" + numeroBoleto + "','" + vencimento +"',"+ valor + ",'"+ descricao + "','"+ dataPagamento + "',"
                + valorPago + ",'"+ metodoPagamento + "','" + operadoraCartao + "','"+ banco + "','"+ agencia + "','"+ conta + "','"+ numeroCheque +"')";
                
                
                Statement stm = con.createStatement();
                stm = con.prepareStatement(sql);
                stm.execute(sql);
                cbxRA1.setSelectedItem(limpacbx);
                tfNumeroBoleto.setText("");
                tfVencimento.setText("");
                tfValor.setText("");
                tfDescricao.setText("");
                tfDataPagamento.setText("");
                tfValorPago.setText("");
                tfMetodoPagamento.setText("");
                tfOperadoraCartao.setText("");
                tfBanco.setText("");
                tfAgencia.setText("");
                tfConta.setText("");
                tfNumeroCheque.setText("");
                CarregarCombo();
                cbxRA1.requestFocus();
                model.setRowCount(0);
                JOptionPane.showMessageDialog( null, "Inclusão realizada com Sucesso! ","Sucesso",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao incluir, tente novamente "+e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String ra, vencimento, dataPagamento;
        int linha = jTable1.getSelectedRow();
        if (linha==-1)
        {
            JOptionPane.showMessageDialog(null,"Você deve selecionar uma linha.");
        }
        else{
            lblPagamentoID.setText((String) jTable1.getValueAt(linha, 0));
            ra = ((String) jTable1.getValueAt(linha, 2));
            cbxRA1.setSelectedItem(ra);
            tfNumeroBoleto.setText((String) jTable1.getValueAt(linha, 3));
            vencimento = (String) jTable1.getValueAt(linha, 4);
            String dia = vencimento.substring(8, 10);
            String mes = vencimento.substring(5, 7);
            String ano = vencimento.substring(0,4);
            vencimento = dia+mes+ano;
            tfVencimento.setText(vencimento);
            tfValor.setText((String) jTable1.getValueAt(linha, 5));
            tfDescricao.setText((String) jTable1.getValueAt(linha, 6));
            dataPagamento = (String) jTable1.getValueAt(linha, 7);
            dia = dataPagamento.substring(8, 10);
            mes = dataPagamento.substring(5, 7);
            ano = dataPagamento.substring(0,4);
            dataPagamento = dia+mes+ano;
            tfDataPagamento.setText(dataPagamento);
            tfValorPago.setText((String) jTable1.getValueAt(linha, 8));
            tfMetodoPagamento.setText((String) jTable1.getValueAt(linha, 9));
            tfOperadoraCartao.setText((String) jTable1.getValueAt(linha, 10));
            tfBanco.setText((String) jTable1.getValueAt(linha, 11));
            tfAgencia.setText((String) jTable1.getValueAt(linha, 12));
            tfConta.setText((String) jTable1.getValueAt(linha, 12));
            tfNumeroCheque.setText((String) jTable1.getValueAt(linha, 13));
            cbxRA1.requestFocus();
            btnGravar.setEnabled(true);
            btnIncluir.setEnabled(false);
            btnConsultar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        try
        {
            String sql;
            String ra = "",numeroBoleto, vencimento, valor, descricao = "";  
            String dataPagamento = "", valorPago="", metodoPagamento="", operadoraCartao="";
            String banco="", agencia="", conta="", numeroCheque="",limpacbx = "Selecione...";
            
            sql = "select RA from Aluno where RA = '" + cbxRA1.getSelectedItem() + "'";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next())
            {
                ra = rs.getString("RA");
            }
            numeroBoleto = tfNumeroBoleto.getText();
            String dia = tfVencimento.getText().substring(0, 2);
            String mes = tfVencimento.getText().substring(3, 5);
            String ano = tfVencimento.getText().substring(6);
            vencimento = ano+"-"+mes+"-"+dia;
            valor = tfValor.getText();
            descricao = tfDescricao.getText();     
            dia = tfDataPagamento.getText().substring(0, 2);
            mes = tfDataPagamento.getText().substring(3, 5);
            ano = tfDataPagamento.getText().substring(6);
            dataPagamento = ano+"-"+mes+"-"+dia;        
            valorPago = tfValorPago.getText();       
            metodoPagamento = tfMetodoPagamento.getText();        
            operadoraCartao = tfOperadoraCartao.getText();      
            banco = tfBanco.getText();       
            agencia = tfAgencia.getText();     
            conta = tfConta.getText();    
            numeroCheque = tfNumeroCheque.getText();     
                               
             if(ra.equals("") || numeroBoleto.equals("") || vencimento.equals("") || valor.equals("") || dataPagamento.equals("") || valorPago.equals("") || metodoPagamento.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Por Favor, preencha os dados corretamente!","ERRO",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                               
                sql="UPDATE Pagamento set RA = '"+ra+"', Numero_Boleto = '"+numeroBoleto+"', Vencimento = '"+vencimento+"'"
                +", Valor = "+valor+", Descricao = '"+descricao+"',Data_Pagamento = '"+dataPagamento+"', Valor_Pago = "+valorPago+""
                +", Metodo_Pagamento = '"+metodoPagamento+"', Operadora_Cartao = '"+operadoraCartao+"', Banco = '"+banco+""
                +"', Agencia = '"+agencia+"', Conta = '"+conta+"',Numero_Cheque = '"+numeroCheque+"' "        
                + "where PagamentoID = "+lblPagamentoID.getText(); 
                
                stm = con.prepareStatement(sql);
                stm.execute(sql);
                cbxRA1.setSelectedItem(limpacbx);
                tfNumeroBoleto.setText("");
                tfVencimento.setText("");
                tfValor.setText("");
                tfDescricao.setText("");
                tfDataPagamento.setText("");
                tfValorPago.setText("");
                tfMetodoPagamento.setText("");
                tfOperadoraCartao.setText("");
                tfBanco.setText("");
                tfAgencia.setText("");
                tfConta.setText("");
                tfNumeroCheque.setText("");
                CarregarCombo();
                cbxRA1.requestFocus();
                model.setRowCount(0);
                btnIncluir.setEnabled(true);
                btnConsultar.setEnabled(true);
                btnAlterar.setEnabled(false);
                btnGravar.setEnabled(false);
                JOptionPane.showMessageDialog( null, "Alteração realizada com Sucesso! ","Sucesso",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao alterar, tente novamente "+e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String sql;
        String nomeResp="",RA = "",limpacbx = "Selecione..."; 
        model.setRowCount(0);
        nomeResp = cbxResp.getSelectedItem().toString();
        RA = cbxRA2.getSelectedItem().toString();    
        try
        {
                    
            sql = "SELECT tabelaPagamento.*,tabelaMatricula.Responsavel_Financeiro as NomeResp, tabelaAluno.RA as RaAluno "
            + "from Aluno tabelaAluno inner join Pagamento tabelaPagamento ON tabelaPagamento.RA = tabelaAluno.RA "
            + "left join matricula tabelaMatricula ON tabelaMatricula.RA = tabelaAluno.RA "
            + " Where 1 = 1 ";
            
            if(!nomeResp.equals("Selecione..."))
            {
                sql = sql + " AND tabelaMatricula.Responsavel_Financeiro  = '" + nomeResp+"'";
            }
          
            if(!RA.equals("Selecione..."))
            {
                sql = sql + " AND tabelaAluno.RA  = '" + RA+"'";
            }
            sql = sql + " order by tabelaAluno.RA";
            
            
            System.out.println(sql);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            rs.first();
            rs.getRow();
            if(rs.getRow() > 0){
                String[] linha = new String[]{rs.getString("PagamentoID"),rs.getString("NomeResp"),rs.getString("RA"),rs.getString("Numero_Boleto"),
                rs.getString("Vencimento"),rs.getString("Valor"),rs.getString("Descricao"),rs.getString("Data_Pagamento"),rs.getString("Valor_Pago"),rs.getString("Metodo_Pagamento"),
                rs.getString("Operadora_Cartao"),rs.getString("Banco"),rs.getString("Agencia"),rs.getString("Conta"),rs.getString("Numero_Cheque")};
                model.addRow(linha);
                while(rs.next())
                {
                    linha = new String[]{rs.getString("PagamentoID"),rs.getString("NomeResp"),rs.getString("RA"),rs.getString("Numero_Boleto"),
                    rs.getString("Vencimento"),rs.getString("Valor"),rs.getString("Descricao"),rs.getString("Data_Pagamento"),rs.getString("Valor_Pago"),rs.getString("Metodo_Pagamento"),
                    rs.getString("Operadora_Cartao"),rs.getString("Banco"),rs.getString("Agencia"),rs.getString("Conta"),rs.getString("Numero_Cheque")}; 
                    model.addRow(linha);
                }
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
                cbxRA2.setSelectedItem(limpacbx);
                cbxResp.setSelectedItem(limpacbx);
            }
            else
            {
                JOptionPane.showMessageDialog( null, "Não existe nenhum Pagamento registrado com essas características","Erro",JOptionPane.INFORMATION_MESSAGE);
                cbxResp.setSelectedItem(limpacbx);
                cbxRA2.setSelectedItem(limpacbx);
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao consultar, tente novamente "+e,"ERRO:",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = jTable1.getSelectedRow();
        if (linha==-1)
        {
            JOptionPane.showMessageDialog(null,"Você deve selecionar uma linha.");
        }
        else
        {
            int opcao = JOptionPane.showConfirmDialog(null,"Confirma exclusão","Excluindo...", JOptionPane.YES_NO_OPTION);
            String sql, codigo;
            codigo = (String) jTable1.getValueAt(linha, 0);
            if (opcao==0)
            {
                try
                {
                    sql="delete from Pagamento where PagamentoID= " + codigo;
                    Statement stm = con.prepareStatement(sql);
                    stm.execute(sql);
                    btnIncluir.setEnabled(true);
                    btnConsultar.setEnabled(true);
                    btnAlterar.setEnabled(false);
                    btnExcluir.setEnabled(false);
                    cbxRA1.requestFocus();
                    CarregarCombo();
                    JOptionPane.showMessageDialog(null, "Exclusão feita com Sucesso! ","Sucesso", JOptionPane.INFORMATION_MESSAGE);
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir, tente novamente " +e,"ERRO: ",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else
            {
                cbxRA1.requestFocus();
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);
            }
            model.setRowCount(0);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxRA1;
    private javax.swing.JComboBox<String> cbxRA2;
    private javax.swing.JComboBox<String> cbxResp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPagamentoID;
    private javax.swing.JTextField tfAgencia;
    private javax.swing.JTextField tfBanco;
    private javax.swing.JTextField tfConta;
    private javax.swing.JFormattedTextField tfDataPagamento;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfMetodoPagamento;
    private javax.swing.JTextField tfNumeroBoleto;
    private javax.swing.JTextField tfNumeroCheque;
    private javax.swing.JTextField tfOperadoraCartao;
    private javax.swing.JTextField tfValor;
    private javax.swing.JTextField tfValorPago;
    private javax.swing.JFormattedTextField tfVencimento;
    // End of variables declaration//GEN-END:variables
}
